// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz1oy_4l3fYM2xVuN9W5pKA9FWXoBCu5w',
    appId: '1:114663718964:web:cfc9d64701d329da31ca61',
    messagingSenderId: '114663718964',
    projectId: 'riceconnect-ed41a',
    authDomain: 'riceconnect-ed41a.firebaseapp.com',
    storageBucket: 'riceconnect-ed41a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIZuP2JYEAQjgIOpXFCCmjJKDvqOHs7WY',
    appId: '1:114663718964:android:b8c21c86b955cab031ca61',
    messagingSenderId: '114663718964',
    projectId: 'riceconnect-ed41a',
    storageBucket: 'riceconnect-ed41a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXlnJ2E8LLhg_iNiyH6SHS3RoJSOtzKkA',
    appId: '1:114663718964:ios:34ad13537e92a2e431ca61',
    messagingSenderId: '114663718964',
    projectId: 'riceconnect-ed41a',
    storageBucket: 'riceconnect-ed41a.firebasestorage.app',
    iosBundleId: 'com.example.riceConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXlnJ2E8LLhg_iNiyH6SHS3RoJSOtzKkA',
    appId: '1:114663718964:ios:34ad13537e92a2e431ca61',
    messagingSenderId: '114663718964',
    projectId: 'riceconnect-ed41a',
    storageBucket: 'riceconnect-ed41a.firebasestorage.app',
    iosBundleId: 'com.example.riceConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz1oy_4l3fYM2xVuN9W5pKA9FWXoBCu5w',
    appId: '1:114663718964:web:d4925baab08cef3131ca61',
    messagingSenderId: '114663718964',
    projectId: 'riceconnect-ed41a',
    authDomain: 'riceconnect-ed41a.firebaseapp.com',
    storageBucket: 'riceconnect-ed41a.firebasestorage.app',
  );
}
